In [1]:
import numpy as np
import pandas as pd 

import seaborn as sns 
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier,VotingClassifier,AdaBoostClassifier,BaggingClassifier
import xgboost as xgb

from sklearn import metrics

In [222]:
from prettytable import PrettyTable

In [248]:
df=pd.read_csv('heart.csv')

In [249]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [250]:
df.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

In [251]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.2 KB


In [252]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

## cross_tab is one of the commonly used method used in EDA 

In [267]:
pd.crosstab(df.target.count(),df.sex)

sex     0    1
row_0         
303    96  207

In [268]:
data = df.copy(deep=True)

# how to handle outliers 

In [269]:
from scipy import stats
data_out = data[np.abs((stats.zscore(data)) < 3) .all(axis=1)].copy()

### above i showed the technique to handle outliers but i did not removed the outliers because in health every report is important and although there are very few rows in give dataset so that is the reason i did not eliminated the outliers

In [270]:
df1_y=df.iloc[:,-1]
df1_x=df.iloc[:,:-1]

In [271]:
x1train,x1test,y1train,y1test=train_test_split(df1_x,df1_y,random_state=43)

In [272]:
sc1=StandardScaler()
X1train=sc1.fit_transform(x1train)
X1test=sc1.transform(x1test)

C:\Users\KRISH8\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\KRISH8\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\KRISH8\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


# Logistic Regression

In [273]:
LR1 = LogisticRegression(random_state=1)
LR1.fit(X1train,y1train)
LR_o_pre = LR1.predict(X1test)


print('accuracy ',metrics.accuracy_score(y1test,LR_o_pre))
print('recall',metrics.recall_score(y1test,LR_o_pre))
print('precision',metrics.precision_score(y1test,LR_o_pre))
print('F1',metrics.f1_score(y1test,LR_o_pre))
print('roc_auc_score',metrics.roc_auc_score(y1test,LR_o_pre))
print(metrics.classification_report(y1test,LR_o_pre))

print(metrics.confusion_matrix(y1test,LR_o_pre))



accuracy  0.8947368421052632
recall 1.0
precision 0.8333333333333334
F1 0.9090909090909091
roc_auc_score 0.8888888888888888
              precision    recall  f1-score   support

           0       1.00      0.78      0.88        36
           1       0.83      1.00      0.91        40

   micro avg       0.89      0.89      0.89        76
   macro avg       0.92      0.89      0.89        76
weighted avg       0.91      0.89      0.89        76

[[28  8]
 [ 0 40]]


C:\Users\KRISH8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [274]:
fpr1, tpr1, threshold = metrics.roc_curve(y1test,LR_o_pre)
roc_auc1 = metrics.auc(fpr1, tpr1)

# DecissionTree

In [276]:
dt1=DecisionTreeClassifier(criterion='gini',random_state=67)
dt1.fit(X1train,y1train)
dt_o_pre = dt1.predict(X1test)

print('accuracy ',metrics.accuracy_score(y1test,dt_o_pre))
print('precision',metrics.precision_score(y1test,dt_o_pre))
print('recall',metrics.recall_score(y1test,dt_o_pre))
print('F1',metrics.f1_score(y1test,dt_o_pre))
print('roc_auc_score',metrics.roc_auc_score(y1test,dt_o_pre))
print(metrics.confusion_matrix(y1test,dt_o_pre))
print(metrics.classification_report(y1test,dt_o_pre))

accuracy  0.7894736842105263
precision 0.8157894736842105
recall 0.775
F1 0.7948717948717949
roc_auc_score 0.7902777777777777
[[29  7]
 [ 9 31]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.78        36
           1       0.82      0.78      0.79        40

   micro avg       0.79      0.79      0.79        76
   macro avg       0.79      0.79      0.79        76
weighted avg       0.79      0.79      0.79        76



In [277]:
fpr2, tpr2, threshold = metrics.roc_curve(y1test,dt_o_pre)
roc_auc2 = metrics.auc(fpr2, tpr2)

# RandomForest

In [278]:
rf_o = RandomForestClassifier(random_state=60,n_estimators=29)
rf_o.fit(X1train,y1train)
rf_o_pre=rf_o.predict(X1test)

print('accuracy ',metrics.accuracy_score(y1test,rf_o_pre))
print('precision',metrics.precision_score(y1test,rf_o_pre))
print('recall',metrics.recall_score(y1test,rf_o_pre))
print('F1',metrics.f1_score(y1test,rf_o_pre))
print('roc_auc_score',metrics.roc_auc_score(y1test,rf_o_pre))
print(metrics.confusion_matrix(y1test,rf_o_pre))
print(metrics.classification_report(y1test,rf_o_pre))


accuracy  0.8157894736842105
precision 0.782608695652174
recall 0.9
F1 0.8372093023255814
roc_auc_score 0.8111111111111111
[[26 10]
 [ 4 36]]
              precision    recall  f1-score   support

           0       0.87      0.72      0.79        36
           1       0.78      0.90      0.84        40

   micro avg       0.82      0.82      0.82        76
   macro avg       0.82      0.81      0.81        76
weighted avg       0.82      0.82      0.81        76



In [279]:
fpr6, tpr6, threshold = metrics.roc_curve(y1test,rf_o_pre)
roc_auc6 = metrics.auc(fpr6, tpr6)

# Bagging

In [286]:
bg_o = BaggingClassifier(DecisionTreeClassifier(),n_estimators=11,random_state=5)
bg_o.fit(X1train,y1train)
bg_o_pre = bg_o.predict(X1test)

print(metrics.accuracy_score(y1test,bg_o_pre))
print(metrics.precision_score(y1test,bg_o_pre))
print(metrics.recall_score(y1test,bg_o_pre))
print(metrics.f1_score(y1test,bg_o_pre))
print(metrics.roc_auc_score(y1test,bg_o_pre))

0.8157894736842105
0.782608695652174
0.9
0.8372093023255814
0.8111111111111111


In [287]:
fpr3, tpr3, threshold = metrics.roc_curve(y1test,bg_o_pre)
roc_auc3 = metrics.auc(fpr3, tpr3)

# AdaBoost

In [288]:
ab_o = AdaBoostClassifier(DecisionTreeClassifier(),random_state=13,n_estimators=20,learning_rate=1)
ab_o.fit(X1train,y1train)
ab_0_pre = ab_o.predict(X1test)
    
print(metrics.accuracy_score(y1test,ab_0_pre))
print(metrics.precision_score(y1test,ab_0_pre))
print(metrics.recall_score(y1test,ab_0_pre))
print(metrics.f1_score(y1test,ab_0_pre))
print(metrics.roc_auc_score(y1test,ab_0_pre))

0.8421052631578947
0.85
0.85
0.85
0.8416666666666667


In [289]:
fpr4, tpr4, threshold = metrics.roc_curve(y1test,ab_0_pre)
roc_auc4 = metrics.auc(fpr4, tpr4)

# Voting classifier

In [344]:
lr=LogisticRegression(random_state=2)
rf =RandomForestClassifier(random_state=60)
svm = SVC(random_state=20,kernel='poly')
nb=GaussianNB()
vc_o = VotingClassifier(estimators=[('lr',lr),('rf',rf),('svm',svm),('nb',nb)],voting='hard')
vc_o=vc_o.fit(X1train,y1train)
vc_0_pre=vc_o.predict(X1test)

print(metrics.accuracy_score(y1test,vc_0_pre))
print(metrics.precision_score(y1test,vc_0_pre))
print(metrics.recall_score(y1test,vc_0_pre))
print(metrics.f1_score(y1test,vc_0_pre))
print(metrics.roc_auc_score(y1test,vc_0_pre))
print(metrics.confusion_matrix(y1test,vc_0_pre))

0.881578947368421
0.8444444444444444
0.95
0.8941176470588236
0.8777777777777778
[[29  7]
 [ 2 38]]


C:\Users\KRISH8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\KRISH8\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [345]:
fpr5, tpr5, threshold = metrics.roc_curve(y1test,vc_0_pre)
roc_auc5 = metrics.auc(fpr5, tpr5)

In [347]:
t = PrettyTable(['Model', 'Accuracy', 'Recall','Precision','F1','roc_auc'])
t.add_row(['Random Forest',82,78,90,84,81])
t.add_row(['Logistic Regression',90,100,83,91,89])
t.add_row(['DecisionTree',79,82,78,79,79])
t.add_row(['Voting Classifier',89,84,95,90,88])
t.add_row(['Bagging',82,77,93,84,81])
t.add_row(['AdaBooating',84,85,85,85,84])

In [348]:
print(t)

+---------------------+----------+--------+-----------+----+---------+
|        Model        | Accuracy | Recall | Precision | F1 | roc_auc |
+---------------------+----------+--------+-----------+----+---------+
|    Random Forest    |    82    |   78   |     90    | 84 |    81   |
| Logistic Regression |    90    |  100   |     83    | 91 |    89   |
|     DecisionTree    |    79    |   82   |     78    | 79 |    79   |
|  Voting Classifier  |    89    |   84   |     95    | 90 |    88   |
|       Bagging       |    82    |   77   |     93    | 84 |    81   |
|     AdaBooating     |    84    |   85   |     85    | 85 |    84   |
+---------------------+----------+--------+-----------+----+---------+
